project_name: Kamailio Dispatchers Manager
builds:
   - binary: dispatchers
     env:
        - CGO_ENABLED=0
     goos:
        - windows
        - darwin
        - linux
     goarch:
        - amd64
     dir: ./cmd/dispatchers
archives:
   - id: dispatchers
     format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
       - '^docs:'
       - '^test:'
dockers:
   - image_templates:
       - "cycoresystems/dispatchers:{{ .Tag }}"
       - "cycoresystems/dispatchers:v{{ .Major }}"
       - "cycoresystems/dispatchers:v{{ .Major }}.{{ .Minor }}"
       - cycoresystems/dispatchers:latest
