apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatchers
  namespace: voip

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-getter
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dispatchers-node-getter
subjects:
  - kind: User
    name: dispatchers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-getter
  apiGroup: rbac.authorization.k8s.io

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dispatchers
  namespace: voip
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods","endpoints","services"]
    verbs: ["get", "watch", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager
  namespace: voip
subjects:
  - kind: User
    name: dispatchers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dispatchers
  apiGroup: rbac.authorization.k8s.io

---

piVersion: apps/v1
kind: DaemonSet
metadata:
  name: kamailio
  namespace: voip
  labels:
    component: kamailio
spec:
  selector:
    matchLabels:
      component: kamailio
  template:
    metadata:
      name: kamailio
      labels:
        component: kamailio
    spec:
      serviceAccountName: dispatchers
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-kamailio
      hostNetwork: true
      volumes:
        - name: config
      containers:
        - name: kamailio
          image: cycoresystems/kamailio
          volumeMounts:
            - name: config
              mountPath: /data/kamailio
        - name: rtpproxy
          image: cycoresystems/rtpproxy
        - name: dispatchers
          image: cycoresystems/dispatchers
          command:
            - /app
            - "-set"
            - default:asterisk=1
          volumeMounts:
            - name: config
              mountPath: /data/kamailio
