apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatchers
  namespace: voip

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-slices
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "watch", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dispatchers-node-getter
subjects:
  - kind: ServiceAccount
    name: dispatchers
    namespace: voip
roleRef:
  kind: ClusterRole
  name: endpoint-slices
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kamailio
  namespace: voip
  labels:
    component: kamailio
spec:
  selector:
    matchLabels:
      component: kamailio
  template:
    metadata:
      name: kamailio
      labels:
        component: kamailio
    spec:
      serviceAccountName: dispatchers
      volumes:
        - name: config
      containers:
        - name: kamailio
          image: cycoresystems/kamailio
          volumeMounts:
            - name: config
              mountPath: /data/kamailio
        - name: rtpproxy
          image: cycoresystems/rtpproxy
        - name: dispatchers
          image: cycoresystems/dispatchers
          command:
            - /app
            - "-set"
            - default:asterisk=1
          volumeMounts:
            - name: config
              mountPath: /data/kamailio
